### ISSUE TITLE
Installation with pip3 failed

### ISSUE THREAD

**Issue by chaica** [ihabunek/toot#10]
Hi,

While trying to install toot with pip3 on Debian Jessie, pip seems to fail:
```
# pip3 install toot --upgrade
Downloading/unpacking toot
  Downloading toot-0.9.1-py2.py3-none-any.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2595, in _dep_map
    return self.__dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2457, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2401, in requires
    dm = self._dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2597, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2621, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2686, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'beautifulsoup4 ~=4.5.3', 'at', ' ~=4.5.3')

Storing debug log for failure in /root/.pip/pip.log
```

Let me know if you need more information.

Cheers,
Carl

**Comment by chaica** [comment]
While trying to install by hand:
```
:~/toot-0.8.0# python3 setup.py install
error in toot setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```

**Comment by dachary** [comment]
Works for me.

<pre>
loic@fold:/tmp/toot$ virtualenv --python=python3 /tmp/v
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /tmp/v/bin/python3
Also creating executable in /tmp/v/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
loic@fold:/tmp/toot$ source /tmp/v/bin/activate
(v) loic@fold:/tmp/toot$ pip3 install toot --upgrade
Collecting toot
  Downloading toot-0.9.1-py2.py3-none-any.whl
Collecting beautifulsoup4~=4.5.3 (from toot)
  Using cached beautifulsoup4-4.5.3-py3-none-any.whl
Collecting future (from toot)
Collecting requests~=2.13 (from toot)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Installing collected packages: beautifulsoup4, future, requests, toot
Successfully installed beautifulsoup4-4.5.3 future-0.16.0 requests-2.13.0 toot-0.9.1
(v) loic@fold:/tmp/toot$ python3 --version
Python 3.5.2
</pre>

**Comment by chaica** [comment]
Debian Jessie uses python 3.4:
```
$ python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by tleb** [comment]
The answer was given by @ihabunek in #8, you need to update `pip` by doing a `pip install --upgrade pip`.

**Comment by cedricbonhomme** [comment]
According to this test on Travis, it is also working with Python 3.4.2:
https://travis-ci.org/ihabunek/toot/jobs/225099577

If you have an up-to-date version of pip, maybe it is an encoding problem.

**Comment by dachary** [comment]
Most likely a pip problem indeed. 
<pre>
loic@fold:/tmp$ virtualenv --python=python3.4 /tmp/v
Running virtualenv with interpreter /usr/bin/python3.4
Using base prefix '/usr'
New python executable in /tmp/v/bin/python3.4
Also creating executable in /tmp/v/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
loic@fold:/tmp$ /tmp/v/bin/pip3 install toot --upgrade
Collecting toot
  Using cached toot-0.9.1-py2.py3-none-any.whl
Collecting requests~=2.13 (from toot)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting future (from toot)
  Using cached future-0.16.0.tar.gz
Collecting beautifulsoup4~=4.5.3 (from toot)
  Using cached beautifulsoup4-4.5.3-py3-none-any.whl
Building wheels for collected packages: future
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /home/loic/.cache/pip/wheels/c2/50/7c/0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
Successfully built future
Installing collected packages: requests, future, beautifulsoup4, toot
Successfully installed beautifulsoup4-4.5.3 future-0.16.0 requests-2.13.0 toot-0.9.1
loic@fold:/tmp$ /tmp/v/bin/python --version
Python 3.4.5
</pre>

**Comment by ihabunek** [comment]
Just pushed `0.10.0` which should fix this problem. 

I stopped using `~=` for dependencies. See acda7cbb945692efbb79a720354de7aec64f1927.

**Comment by srnit** [comment]
just install them using --user option which install the package only for the current user and not for all

pip install xxxxxx --user
