### ISSUE TITLE
Unable to login to mstdn.jp, 403 error

### ISSUE THREAD

**Issue by maptile** [ihabunek/toot#106]
When I login mstdn.jp account using the following command `toot login --instance mstdn.jp --debug`, toot shows the following error.

> Looking up instance info...
> DEBUG:toot:>>> GET https://mstdn.jp/api/v1/instance
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mstdn.jp:443
> DEBUG:urllib3.connectionpool:https://mstdn.jp:443 "GET /api/v1/instance HTTP/1.1" 403 None
> DEBUG:toot:<<< <Response [403]>
> DEBUG:toot:<<< b'\<!DOCTYPE html> <html class="no-js" lang="en-US"> <head><title>Access denied | mstdn.jp used Cloudflare to restrict access</title><meta charset="UTF-8" /><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /><meta name="robots" content="noindex, nofollow" /><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" /><link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" /><style type="text/css">body{margin:0;padding:0}</style><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script></head><body>  <div id="cf-wrapper">    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>    <div id="cf-error-details" class="cf-error-details-wrapper">      <div class="cf-wrapper cf-header cf-error-overview">        \<h1>          <span class="cf-error-type" data-translate="error">Error</span>          <span class="cf-error-code">1020</span>          <small class="heading-ray-id">Ray ID: 502835898xxxxxxxx &bull; 2019-08-07 09:26:28 UTC</small>        </h1>        \<h2 class="cf-subheadline">Access denied</h2>      </div>      <section></section>      <div class="cf-section cf-wrapper">        <div class="cf-columns two">          <div class="cf-column">            \<h2 data-translate="what_happened">What happened?</h2>            <p>This website is using a security service to protect itself from online attacks.</p>          </div>                  </div>      </div>      <div class="cf-error-footer cf-wrapper">  <p>    <span class="cf-footer-item">Cloudflare Ray ID: \<strong>502835898xxxxxxxx</strong></span>    <span class="cf-footer-separator">&bull;</span>    <span class="cf-footer-item"><span>Your IP</span>: xxx.xxx.xxx.xxx</span>    <span class="cf-footer-separator">&bull;</span>    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>      </p></div>    </div>  </div>  <script type="text/javascript">  window._cf_translation = {};    </script></body></html>'
> Unknown error

It seems that it is Cloudflare send this error. And in error message, it shows the useragent should 
 enable cookie to pass the access check. 

Can this problem be fixed in toot? Or is there some workarounds?

Thanks.

**Comment by ihabunek** [comment]
@maptile Seems like Clodfare can be appeased by by setting a `User-Agent` header on requests. I've set it to `toot/<version>` and that seems to work fine.

**Comment by maptile** [comment]
@ihabunek I've updated the code, and it WORKS! Thanks you.
