### ISSUE TITLE
check default permissions on config creation!

### ISSUE THREAD

**Issue by cremesk** [ihabunek/toot#109]
Hello,

i have installed "toot" on Debian 10.
Then i use it the first time i use:
`toot login_cli`

after authentication the access token saved to: `~/.config/toot/config.json`

this file needs: `chmod 600 ~/.config/toot/config.json`!
i think i not posible then other user can read the secrets.

pls fix it by default!

Thanks

**Comment by ihabunek** [comment]
@cremesk Fixed, thanks for reporting, that totally went over my head when writing the code.
