### ISSUE TITLE
`toot tui` results in a "ValueError: time data […]"

### ISSUE THREAD

**Issue by Hund** [ihabunek/toot#114]
I installed the latest version of toot on my Gentoo box and when I run `toot tui` I'm greeted with this:

![2019-09-03-210841_788x468_scrot](https://user-images.githubusercontent.com/320498/64201460-10434500-ce8f-11e9-85c2-230c1e93bc07.png)

* Python 3.6.5
* toot 0.23.0
* requests 2.21
* beautifulsoup 4.5.1
* wcwidth 0.1.7

**Comment by ihabunek** [comment]
Seems that in Python versions <3.7 `%z` does not match `Z` as offset. Also, it does not match `±HH:MM` offsets, only `±HHMM` which could be sent by a server (although I haven't yet seen it).

See note 6 here:
https://docs.python.org/3.7/library/datetime.html#strftime-and-strptime-behavior

**Comment by ihabunek** [comment]
Should be fixed in https://github.com/ihabunek/toot/releases/tag/0.23.1
Please verify.

**Comment by Hund** [comment]
Verson 0.23.1 solves it. Thanks! :)
