### ISSUE TITLE
Feature request: Show toot character count on TUI

### ISSUE THREAD

**Issue by Aicaya** [ihabunek/toot#121]
Would be useful to know how many characters a toot has while composing, to prevent both errors and unwanted splitting (in case [that feature request][1] is applied). Could also make the counter change colors once it goes past the character limit to warn the user, and possibly add an option to raise the limit in a configuration file in case it's a server with a much higher character limit.

[1]: https://github.com/ihabunek/toot/issues/64

**Comment by ihabunek** [comment]
I've implemented the character count and attempt to load it from the server on init. Unfortunately, this is [not supported by Mastodon](https://github.com/tootsuite/mastodon/issues/4915), but Pleroma supports it at least.

I'll open another issue for overriding the char count per server. 

This change will be released in next version.

**Comment by ihabunek** [comment]
Released in v0.25.0.

TODO: #143
