### ISSUE TITLE
# in Hashtag search causes breakage

### ISSUE THREAD

**Issue by ndowens** [ihabunek/toot#134]
http://ndowens.cf/bug/toot.png

How to reproduce:
Inside toot tui, press G, in Hashtag: put #ANYTAG-HERE and select local or remote.

I know no need to put # in the input, figured that out afterwards, but thought I would let you know.

**Comment by Moult** [comment]
+1 :) sounds like a relatively simple fix, as it could just be stripped?

**Comment by ihabunek** [comment]
Fixed by url-quoting the search string. Released in v0.25.0.
