### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by aadilayub** [ihabunek/toot#135]
Using the search command gives the response of `Unknown error`.

![image](https://user-images.githubusercontent.com/31581044/67918797-abbb1280-fbbf-11e9-9b60-eefb5a3cff72.png)

I'm using toot on Fedora 31, installed using pip.

**Comment by ihabunek** [comment]
Fixed by upgrading to [search v2](https://docs.joinmastodon.org/methods/search/), v1 has been removed. 
Released in v0.25.0.
