### ISSUE TITLE
Bug: Need non-zero exit on error

### ISSUE THREAD

**Issue by pacohope** [ihabunek/toot#14]
I have a job that sometimes produces text too big to toot. That's OK, I'll just retry with a smaller amount of text. But the 'toot post' command exits with error code '0' to the shell. So my shell script can't tell that the attempt to toot failed with an error.

Example:
```
$ cat bigfile.txt | toot post
Validation failed: Text character limit of 500 exceeded
$ echo $?
0
```

When there's no error, the 'toot' command should exit 0. When there's any kind of error, the command should exit non-zero. Some sample exit codes are here: http://www.tldp.org/LDP/abs/html/exitcodes.html

I'm using version 0.11.0 installed via pip.

**Comment by ihabunek** [comment]
@pacohope Fixed in `0.12.0`. toot will use exit code 1 on error.
