### ISSUE TITLE
Notifications, fonts, and attachments in TUI

### ISSUE THREAD

**Issue by Moult** [ihabunek/toot#141]
A few issues bundled into this bugreport, the first is a simple one:

1. I did not see any documentation on how to compose a new toot from `toot tui`. I had to guess that it was `c`. It would be good to add it to the help menu perhaps?
2. I didn't see any way to see notifications from the tui. Is there a way?
3. For systems which don't have the fancy font which shows the icons for stars / boosts / replies, can it just show plain text rather than nothing?
4. How do I attach a file from the `c` command in `toot tui`?

**Comment by ihabunek** [comment]
> I did not see any documentation on how to compose a new toot from toot tui. I had to guess that it was c. It would be good to add it to the help menu perhaps?

It is in the help menu, the second command:

![00004](https://user-images.githubusercontent.com/482138/71713869-c736d980-2e0b-11ea-806c-73a0715ea620.png)

> I didn't see any way to see notifications from the tui. Is there a way?

This is not yet implemented.

> For systems which don't have the fancy font which shows the icons for stars / boosts / replies, can it just show plain text rather than nothing?

That should be configurable, but I don't have a user editable config file in place yet. I'll keep it in mind for future.

> How do I attach a file from the c command in toot tui?

This is not yet implemented.

**Comment by Moult** [comment]
Thanks for the reply! We'll leave this issue open for the remaining issues :) are they simple?

**Comment by ihabunek** [comment]
I'll open separate issues and close this one, it's easier to track them that way.

Notifications are tricky, I still don't have a clear vision how to best integrate them. Attaching media and user settings (to disable or override current unicode symbols) should be easier. The timeline depends on my workload and motivation though, I won't make any promises.

**Comment by Moult** [comment]
No worries :)

I think the most important aspect of notifications is to see replies to your toots, so that you can respond. Not sure if that's easier than the boosts / stars aspect of notifications. Perhaps it can be part of the "Go to / switch timelines" menu.
