### ISSUE TITLE
Implement user settings

### ISSUE THREAD

**Issue by ihabunek** [ihabunek/toot#145]
It would be nice if users could override default toot settings, especially for TUI, for example to change the color scheme or symbols used for boost/retweet (see #141).

**Comment by waynew** [comment]
Not sure if this is part of this issue - but it would be awesome to set my default visibility to private, rather than having to pass the flag every time

**Comment by dimkard** [comment]
I would like to work on this. @ihabunek do you have any approach in mind?

**Comment by ihabunek** [comment]
I have some ideas. I'll get back to you over the weekend hopefully.

**Comment by ihabunek** [comment]
@dimkard Of course I didn't get back to you. Sorry. However there is movement. Work in progress here: #377

**Comment by ihabunek** [comment]
Implemented in 0.38.0
https://toot.bezdomni.net/settings.html
