### ISSUE TITLE
Feature Request: Disable color

### ISSUE THREAD

**Issue by pacohope** [ihabunek/toot#15]
The output of the commands always seems to include the ANSI color codes. I was doing the following:
```
followers=$(toot whois <user> | grep Followers | cut -d : -f 2)
```
But then I want to do things like
```
if [ $followers -gt 10 ]
```
The problem is that the output has ANSI codes in it. So the actual value of $followers is:
```
 ^[[33m1^[[0m
```
Can I get some kind of command line option or config option to disable the color output?

**Comment by ihabunek** [comment]
@pacohope Fixed in `0.12.0`. You can set the `--no-color` option on any command to disable ANSI color.
