### ISSUE TITLE
Reverse order of notifications

### ISSUE THREAD

**Issue by kflak** [ihabunek/toot#151]
Thanks for a great tool! I am curious if it is possible to reverse the order of the notifications? Now, after issuing `toot notifications` I need to scroll back up in the terminal to see the latest notifications. `toot notifications | head` kind of works, but loses me the coloring.

**Comment by githubgnulinux** [comment]
Agree. Please allow information to be viewed in chronological order; much more efficient with the all-powerful command terminal window! :)

**Comment by githubgnulinux** [comment]
From command terminal help:
toot timeline --help
...
-r, --reverse         Reverse the order of the shown timeline
...

so:

toot timeline -r

Thanks for this feature.

**Comment by ihabunek** [comment]
This is added and will be included in 0.27.0.
