### ISSUE TITLE
The explanations of "Unlisted" and "Private" are reversed.

### ISSUE THREAD

**Issue by finnoleary** [ihabunek/toot#152]
The interface says:
> Private - Do not post to public timelines
> Unlisted - Post to followers only
However posts with the visibility "Private", later viewed on the web, show up with a visibility status as "Unlisted", and vice versa.

**Comment by ihabunek** [comment]
Good catch, thanks! Merged manually. 

Just please wrap commit messages to 72 chars in the future. Here's a nice and short guide: https://commit.style/
