### ISSUE TITLE
image in ascii/ansi

### ISSUE THREAD

**Issue by b4zz4** [ihabunek/toot#158]
A conversor of imagenes to text: asciiart, jp2a, img2ansi

**Comment by ihabunek** [comment]
I'm not sure about this. It would require downloading all images and converting them which would require a non trivial amount of bandwidth and CPU power. Ideally the images would be downloaded and processed as soon as the list of statues is fetched so they can be shown immediately when you open a message. I'd only do if it was an opt-in setting, and I don't have settings figured out yet.

I'll leave the issue open, but it will not be a priority.

**Comment by b4zz4** [comment]
Real. I use viewer in framebuffer. Maybe it is priority accept config of mailcap
