### ISSUE TITLE
line break with toot post

### ISSUE THREAD

**Issue by chaica** [ihabunek/toot#16]
Hi,

I was not able to add a line break while using toot post, am I missing something?

Cheers,
Car

**Comment by ihabunek** [comment]
Hm... i can confirm that this does not result in a linebreak, but a literal "\n":

```
toot post "hello\nthere"
```

However, this works:

```
echo "hello\nthere" | toot post 
```

Not exactly sure why. Will have a look over the weekend.

In future, when reporting an issue, please say what you tried. Ideally send a command which reproduces the problem. That makes my life a lot easier.

**Comment by chaica** [comment]
> However, this works:
> 
> echo "hello\nthere" | toot post 

It does not work either with the latesst checkout of the Github repository:
```
 echo "test\ntest" | toot post
Toot posted: https://mastodon.social/@carlchenet/7906988
```
See the image below for the displayed result. The like break does not work.
![toot-post](https://cloud.githubusercontent.com/assets/4236195/26752403/44183d7c-484f-11e7-9502-c359bfca9669.png)

**Comment by chaica** [comment]
any update on this topic?

**Comment by ihabunek** [comment]
I played around with this and it basically depends on how your shell works. Here are some potential solutions.

In bash you can use a special syntax:

```
> toot post $'foo\nbar'
```

In sh/bash/fish you can add an actual new line by pressing Shift+Enter:

```
> toot post "Hello
dquote> World"
```

If that doesn't work, you can use `printf` to parse the string and pipe that into :

```
> printf "Hello\nWorld" | toot post
```

I know I could just expand `\n` into a newline, but then it might make sense to expand other escape sequences, and what if someone actually wants to post literal "\n". I would rather not open that can of worms. :)

**Comment by chaica** [comment]
@ihabunek thanks for your last post, it solved my issue.

**Comment by Hund** [comment]
A little late reply, but you can use `echo` if you add the flag `-e` which enables interpretation of backslash escapes. :)
