### ISSUE TITLE
Configurable colors in TUI

### ISSUE THREAD

**Issue by dg01d** [ihabunek/toot#161]
Feature Request rather than a bug.

It would be useful to permit setting of TUI colors in config file.

Depending on the user's terminal settings, the default colors can be somewhat unreadable, especially for someone of the (ahem) more vintage persuasion.

**Comment by roadriverrail** [comment]
I'm actually quite interested in this myself and I'd even try working on it.  I'm using a color-limited ANSI terminal (Spectrum on Apple iigs).  The TUI also doesn't respect terminal locales; I can't render UTF-8 characters.

I'd work on this directly if I could just iterate on it, but I'm a C and assembly hacker more than a Python hacker.  @ihabunek how do I run this from a git checkout so I can iterate on this?

**Comment by ch1r0x** [comment]
+1

**Comment by ihabunek** [comment]
Implemented in 0.38.0
Docs: https://toot.bezdomni.net/settings.html#tui-color-palette

**Comment by ihabunek** [comment]
@roadriverrail Sorry I never got back to you. Must have missed the mention.
I have added a guide to the docs in the meantime: https://toot.bezdomni.net/contributing.html#setting-up-a-dev-environment
