### ISSUE TITLE
My instance is private and requires authentication to get public timeline.

### ISSUE THREAD

**Issue by hyx0329** [ihabunek/toot#168]
toot version: 0.26.0 from AUR

Here is the debug info.
```bash
$ toot timeline --public --local --debug -c 1
DEBUG:toot:>>> GET https://{INSTANCE_HOST}/api/v1/timelines/public
DEBUG:toot:>>> HEADERS: {'User-Agent': 'toot/0.26.0'}
DEBUG:toot:>>> PARAMS:  {'local': 'true', 'limit': 1}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): me.ns.ci:443
DEBUG:urllib3.connectionpool:https://{INSTANCE_HOST}:443 "GET /api/v1/timelines/public?local=true&limit=1 HTTP/1.1" 422 None
DEBUG:toot:<<< <Response [422]>
DEBUG:toot:<<< b'{"error":"This method requires an authenticated user"}'
This method requires an authenticated user
```
Where "{INSTANCE_HOST}" stands for my instance's address.

I did a quick test using my firefox browser. All GET requests without cookies(auth?) will be rejected by the server.

I also checked that I can get public timeline without authentication at "mastodon.social".

I'm using Tusky on my phone and it's working properly with my instance.

The related cookies' key names are:
+ _mastodon_session
+ _session_id
+ remember_user_token

I read the code about getting public timeline, and found no user information passed. 
https://github.com/ihabunek/toot/blob/bc96cf7eea7e7372fff6ec1bd0446dffd4184372/toot/api.py#L189

Maybe a small patch is required?

**Comment by ihabunek** [comment]
@hyx0329 I've changed the code to use an authorized get request to fetch the timeline (3b5769a). Planing to release 0.27.0 soon.
