### ISSUE TITLE
Feature Request: Change timelines within the TUI

### ISSUE THREAD

**Issue by pard68** [ihabunek/toot#170]
Like the title says, it would be nice to be able to change the timeline being viewed from within the TUI. I mostly just look at the local timeline on Mastadon and don't follow anyone so using the TUI is mostly just my own toots. It'd be nice if I could change to view different timelines so I could view the local instance's timeline or the federated timeline.

**Comment by ihabunek** [comment]
Press `G` :)

**Comment by pard68** [comment]
Thank you!
