### ISSUE TITLE
License link reads GPLv3 but leads to MIT

### ISSUE THREAD

**Issue by Adonai** [ihabunek/toot#173]
I'm confused.

https://github.com/ihabunek/toot/blame/master/README.rst#L14

This is also true for the [readthedocs](https://toot.readthedocs.io/en/latest/) page

**Comment by ihabunek** [comment]
GPL is correct. I'll fix the link.

**Comment by Adonai** [comment]
Thanks!

**Comment by ihabunek** [comment]
Fixed.

**Comment by davidbrochart** [comment]
Would you be open to re-license to something more permissive like MIT?
