### ISSUE TITLE
How do I donate?

### ISSUE THREAD

**Issue by Adonai** [ihabunek/toot#174]
Hello!

Want to make one-time donation to this project, what are my options?

**Comment by ihabunek** [comment]
Hi. Thanks but I'm not accepting donations currently. If you wish you can donate to a local cat sanctuary via Paypal: prava.sapa@gmail.com. They take care of strays in Zagreb and are fully voluntary and always strapped for cash for paying vet debts.

**Comment by Adonai** [comment]
Just donated, thanks.

**Comment by ihabunek** [comment]
Thank you.
