### ISSUE TITLE
Copy link to clipboard in TUI

### ISSUE THREAD

**Issue by macxcool** [ihabunek/toot#184]
It would be nice to be able to copy links in the TUI into the selection or the clipboard using a hotkey.

**Comment by ihabunek** [comment]
Planned, but not as simple as it sounds since there is no single way to interact with the clipboard across various operating systems. Each has its own problems, and I only use Linux at the moment.

**Comment by arttu-karpinlehto** [comment]
Maybe "pipe link to configurable command"?  Users could set whatever works in their environment, like xclip, or send it over socket with socat, nc, etc.

**Comment by macxcool** [comment]
> Maybe "pipe link to configurable command"? Users could set whatever works in their environment, like xclip, or send it over socket with socat, nc, etc.

That would certainly be good enough for me.

**Comment by danschwarz** [comment]
0.36 has support for a Cop[y] command; if your terminal software supports [OSC 52](https://www.reddit.com/r/vim/comments/k1ydpn/a_guide_on_how_to_copy_text_from_anywhere/). Some terminal software, such as Windows Terminal, works out of the box,  but others such as Xterm require additional configuration settings to allow copy-to-clipboard.  `allowWindowOps: true`
