### ISSUE TITLE
Making a toot in TUI sends you back to the beginning of the timeline. Even if you reply to a thread.

### ISSUE THREAD

**Issue by newissuemaker** [ihabunek/toot#188]
This ruins the browsing experience and I can't daily drive toot because of this. It's good for posting a thing or two and checking notifications from cli but it's not usable for longer browsing sessions in TUI.

**Comment by marathone** [comment]
Indeed, puzzling behaviour and the reason I don't use this app. I prefer to use a cli app but like @newissuemaker said, it ruins the experience!

**Comment by danschwarz** [comment]
I think this is happening because the TUI rebuilds the timeline from scratch. It may be possible to save/restore the timeline position across timeline rebuilds.
