### ISSUE TITLE
Toot curses not working

### ISSUE THREAD

**Issue by JSewell-Git** [ihabunek/toot#20]
I have installed toot via pip3 (python3-pip). I have tried the `toot curses` command but this is returned:

> 
> Traceback (most recent call last):
>   File "/usr/local/bin/toot", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/toot/console.py", line 285, in main
>     run_command(app, user, command_name, args)
>   File "/usr/local/lib/python2.7/dist-packages/toot/console.py", line 262, in run_command
>     return fn(app, user, parsed_args)
>   File "/usr/local/lib/python2.7/dist-packages/toot/commands.py", line 176, in curses
>     TimelineApp(generator).run()
>   File "/usr/local/lib/python2.7/dist-packages/toot/app.py", line 40, in run
>     curses.wrapper(self._wrapped_run)
>   File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
>     return func(stdscr, *args, **kwds)
>   File "/usr/local/lib/python2.7/dist-packages/toot/app.py", line 57, in _wrapped_run
>     self.full_redraw()
>   File "/usr/local/lib/python2.7/dist-packages/toot/app.py", line 134, in full_redraw
>     self.draw_statuses(self.left)
>   File "/usr/local/lib/python2.7/dist-packages/toot/app.py", line 181, in draw_statuses
>     self.draw_status_row(window, status, offset, highlight)
>   File "/usr/local/lib/python2.7/dist-packages/toot/app.py", line 173, in draw_status_row
>     window.addstr(offset + 4, 1, '─' * (width - 2))
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-57: ordinal not in range(128)

**Comment by ihabunek** [comment]
@JSewell-Git I have dropped the support for python 2 which was making it difficult to easily support unicode. Could you check again if this still happens? Which terminal do you use?

**Comment by JSewell-Git** [comment]
Hey @ihabunek,

I no longer have an Mastodon account. Since I faced this issues several months ago I'm not 100% on what software I was using exactly. I think I was on Ubuntu using the default terminal.

Sorry I cannot re-test to see if this issue is still present.
