### ISSUE TITLE
Wrong times displayed in timeline

### ISSUE THREAD

**Issue by Zwijgmans** [ihabunek/toot#210]
When reading a timeline, the times of posting displayed after 'toot tui' are correct, but after 'toot timeline' they are off by one hour

**Comment by mmmmmmbeer** [comment]
I'm noticing something similar and have a theory - will look into the code in a bit.

toot tui times are correct for me, showing the correct local time (EST, for me)
toot timeline times are four hours off, so I suspect they are UTC.

**Comment by mmmmmmbeer** [comment]
@Zwijgmans I just put in a pull request for this (#212), but if you're impatient take a look at the proposed changes - it's a quick fix, just a couple lines in toot/output.py

**Comment by Zwijgmans** [comment]
Thank you, looks promising. I'll wait for it, though.

**Comment by ihabunek** [comment]
Fixed by #212
