### ISSUE TITLE
Follow from within TUI (feature request)

### ISSUE THREAD

**Issue by bomeara** [ihabunek/toot#221]
Within TUI, if I see a toot boosted by someone I follow, it would be great to be able to follow the creator of the original toot from within TUI (i.e., userA@instance boosts a toot from userB@instance -- I want to be able to follow userB). As is, there's no easy way to do this: I can't even use my mouse to copy the user name. Maybe keybinding for A for Add a user to your follows?

**Comment by danschwarz** [comment]
You can do this as of 0.36.  Here's how:

1. Press [A] to see the Account overlay
2. The account overlay has a follow button. Press Enter to follow , then Enter again to confirm follow.
3. Press [ESC] to exist Account overlay.
