### ISSUE TITLE
Request to send DMs using toot

### ISSUE THREAD

**Issue by dfl1955** [ihabunek/toot#230]
I'd like to be able to send private/direct messages using toot. Could you expose the 'visibility' setting on the command line?

**Comment by ruario** [comment]
Oh yes another thing I would love to see

**Comment by ihabunek** [comment]
On mastodon DMs are normal posts with visibility set to "direct". Only mentioned users will see the post. E.g. 

```
toot post --visibility direct "@ihabunek private message goes here" 
```

See: https://docs.joinmastodon.org/user/posting/#direct

**Comment by dfl1955** [comment]
That seems to work, thanks. Sorry I couldn't find the documentation myself.
