### ISSUE TITLE
Do you have a build & run guide for toot?

### ISSUE THREAD

**Issue by danschwarz** [ihabunek/toot#233]
I have a few contributions I'd like to make to the toot tui, but Python is not a language I use regularly, so I'm having a bit of trouble building and testing my changes. I'm familiar with running .py files with Python, but when I try to do that with tui/app.py, it complains about missing dependencies.  How should I launch the toot tui after making changes? Thx.

**Comment by ihabunek** [comment]
I need to set up a contribution guide. For now, here is how I set up a dev environment.

First time setup:

```
git clone git@github.com:ihabunek/toot.git
cd toot

# Create and activate a virtual environment
python3 -m venv venv
. ./venv/bin/activate

# Install toot and deps into the virutal env
pip install --editable .
```

If you're running windows, then the virtual env is activated like this instead:

```
venv\Scripts\activate.bat
```

If you run `which toot` it should point to the one inside the virtual env. Now you can change the code and run `toot tui` (or other commands) and see the changes.

**Comment by danschwarz** [comment]
Thanks, that worked, did some hacking and emailed you a patch for a timeline update command

**Comment by ihabunek** [comment]
I put together a short guide here:
https://github.com/ihabunek/toot/blob/master/CONTRIBUTING.md#setting-up-a-dev-environment
