### ISSUE TITLE
replace hardcoded image viewers with standard xdg-open

### ISSUE THREAD

**Issue by ethael** [ihabunek/toot#234]
please use standard xdg_open in function show_media from toot/tui/utils.py for opening images

just remove all method code except last line and replace viewer with 'xdg-open'

**Comment by ihabunek** [comment]
`xdg-open` opens only one file, what do you suggest to do when there are multiple images attached?

**Comment by ethael** [comment]
oh. I wasn't aware about that. my fault. 
then the only solution that comes to my mind is parsing .config/mimeapps.list manually and using the preferred app for the mime type. something like:

`cat .config/mimeapps.list | grep image/jpg | awk -F '=' '{print $2}'`

but then you would have to check the location of the .desktop file in both ~/.local/share/applications and /usr/share/applications and parse the found desktop file for 'Exec' line. something like this:

cat /usr/share/applications/feh.desktop | grep Exec | awk -F '=' '{print $2}' | sed 's/%u/paths/'

I don't know how much business logic you plan for config, but it may be the just a bit more effort to implement config file with settings like you mention in the comments, when compared to make these two lines "production ready"

in any case, I will close this now. My original quick fix is not viable. sorry for taking your time. thank you for quick reply.

**Comment by ihabunek** [comment]
Thanks for the suggestion, but yeah, it's not trivial and that's why I haven't solved this. I plan to implement a settings file, but haven't gotten around to it yet.
