### ISSUE TITLE
Sending a toot with only an image

### ISSUE THREAD

**Issue by thebitstick** [ihabunek/toot#24]

**Comment by ihabunek** [comment]
@thebitstick Mastodon won't let me post a toot without text. It returns an error saying "Text can't be blank".
The web interface won't let you do that either. You need to provide some text.

**Comment by thebitstick** [comment]
I can post just an image just fine on the web interface though.
http://i.imgur.com/IEGjmwZ.png
http://i.imgur.com/d7BQkoN.png

Could you just add the image link text?
