### ISSUE TITLE
Stay on timeline when refreshing

### ISSUE THREAD

**Issue by j0ru** [ihabunek/toot#253]
Hey, I just started using toot and really like it so far!
One minor thing I noticed is that when refreshing the timeline, it always switches back to the Home timeline.
It's definitely no game breaker, but I would intuitively expect it to stay on the currently viewed timeline.
I'm currently on version 0.31.0 but I also tried master branch (f9fef19)

Thanks for the app!

**Comment by danschwarz** [comment]
Fixed with PR #338 , fix is in 0.36
