### ISSUE TITLE
Curses client is incomplete

### ISSUE THREAD

**Issue by ihabunek** [ihabunek/toot#28]
The `toot curses` app is incomplete. Implementing it directly in [curses](https://docs.python.org/2/howto/curses.html), as is used now, is a pain in the ass. I have also tried [urwid](http://urwid.org/) which is slightly better, but still consumed too much time to get anything done. 

See current app:
https://github.com/ihabunek/toot/blob/master/toot/app.py

If someone is interested in working on the curses app, I would welcome the help.

**Comment by beli3ver** [comment]
Is there a way to update the stream?

**Comment by beli3ver** [comment]
Maybe a possibilty to post  in the client would be nice

**Comment by ihabunek** [comment]
Note to self: check out https://github.com/jquast/blessed

**Comment by tleb** [comment]
I have heard good things about termbox, which seems to fit the needs of the app:

> It is based on a very simple abstraction. The main idea is viewing terminals as a table of fixed-size cells and input being a stream of structured messages.

Main repo: https://github.com/nsf/termbox (link for the python bindings in the README).

**Comment by ihabunek** [comment]
@tleb thanks, I'll check it out.

**Comment by ihabunek** [comment]
Tried out [asciimatics](http://asciimatics.readthedocs.io/en/stable/) over the weekend. It's actually pretty nice to use, but seems to be pretty sluggish compared to base curses. E.g. Holding the down arrow when navigating over a list of items produces jaggedy jumps. Resizing the screen causes a ~1s delay while it's redrawn again. Not sure this is the way to go.

**Comment by ihabunek** [comment]
No app is ever finished but it's usable now. Will continue working on it using plain curses for now.
