### ISSUE TITLE
H key in TUI is advertised as both cursor movement + Help; can't do both.

### ISSUE THREAD

**Issue by danschwarz** [ihabunek/toot#280]
H as move-left doesn't have much use now, but if pull request #277  is merged, move-left and move-right will be useful to move focus from timeline list to status detail and back again.

Suggestion: change the TUI to use '?' for help instead

<img width="626" alt="image" src="https://user-images.githubusercontent.com/3261094/210158360-fca9c83d-5cb1-4b6c-b51c-7c04fa035950.png">

**Comment by ihabunek** [comment]
`?` sounds good. `L` will have the same problem as it shows links.

**Comment by danschwarz** [comment]
Might want to remove the vi key navigation in that case. I wouldn't want to lose [L]inks.  It's your call, though.

**Comment by ihabunek** [comment]
Yeah, I'll probably just keep J and K for now. I have plans to introduce user-customizable key mappings at some point.

**Comment by hackerb9** [comment]
I'm one of the weirdos who prefers vi key mappings for quick navigation without taking my hands off the homerow. But I get that HJKL may go away, so instead I'll ask: Are the user-customizable key mappings coming before that time? I noticed that somebody created an issue with proposed code for it.

**Comment by danschwarz** [comment]
I think @ihabunek has a plan for a config settings UI and customizable key bindings (among other features) are waiting on that UI. But I'm not sure. Seems like this could be implemented with bindings in config.json, even before a UI is available.
