### ISSUE TITLE
-- description doesnt work

### ISSUE THREAD

**Issue by 7eter** [ihabunek/toot#289]
when using: `toot post "test" --media test.png --description "text"`
i get: `toot post: error unrecognized arguments: --description text`

**Comment by ihabunek** [comment]
That's strange, it works for me. 

![image](https://user-images.githubusercontent.com/482138/213393718-8bab5600-fec2-4e45-8867-342fc7da9c6d.png)

What version are you using?

**Comment by 7eter** [comment]
I'm running toot v0.27.0 and this is what i get when using description:
![image](https://user-images.githubusercontent.com/15588476/213577519-56e003d5-7778-4c53-be09-c3a79d64671b.png)
without description it works just fine!

**Comment by ihabunek** [comment]
Description was added in a later version. You need to upgrade.
