### ISSUE TITLE
Support for 2FA?

### ISSUE THREAD

**Issue by bignimbus** [ihabunek/toot#3]
I have two-factor auth enabled for my Mastodon account.  Whenever I try to `toot login` with the correct email and password, I get the error message `Login failed`.  Does this client support 2FA?

Thanks so much!

**Comment by ihabunek** [comment]
Not currently. I will look into supporting 2FA.

**Comment by vext01** [comment]
Same problem here.

**Comment by ihabunek** [comment]
@bignimbus @vext01 I just released version 0.7.0 which adds experimental 2FA support. could you please try it out and let me know if it works for you?

Instead of `toot login`, use `toot 2fa`.

**Comment by bignimbus** [comment]
@ihabunek works great on my machine.  You are awesome!

**Comment by vext01** [comment]
I'm also able to login with 2fa. Thanks
