### ISSUE TITLE
Cannot reply to notifications

### ISSUE THREAD

**Issue by ploum** [ihabunek/toot#310]
Unless I’m mistaken, there’s no way to :

- see notifications in the tui
- reply to a given toot from cli

Which means there’s no way to reply to notifications (unless I’m missing something).

(sidenote : there’s also no way to "view" a notification or, for the matter, any toot from the CLI)

**Comment by ruario** [comment]
It does now with the release of 0.35.0. There is a new `toot notifications` CLI option. Also you can use `toot post` with the `--reply` switch and the ID of the message you are replying to.

**Comment by ruario** [comment]
Sorry both of those are CLI options. I missed that you wanted a TUI view of notifications.

**Comment by ploum** [comment]
Thanks, will try that once it hits Debian repositories :-)

**Comment by ruario** [comment]
I would recommend running each of those (`toot post`, `toot thread`, `toot notifications` and `toot timeline`) with `--help` first to see all the options. I also initially missed that post can also do replies but requires `-r` (or `--reply-to`).

**Comment by danschwarz** [comment]
TUI has Notifications view as of 0.36  
![image](https://github.com/ihabunek/toot/assets/3261094/f763c96d-a283-45f1-8fc6-35728dc6f549)
