### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by jeroenpraat** [ihabunek/toot#32]
I tried to find if it's possible to use multiple accounts, but I couldn't find it. So maybe it's possible, but I didn't find it, or this is a feature request.

**Comment by ihabunek** [comment]
@jeroenpraat I found some time to work on this. It would help me greatly if you could test out the new changes. They can be found in PR #36.

The configuration is now stored in a single JSON file, your current config should be migrated automatically. Old config is not deleted, so it's easy to move back to the current stable version.

You can log into multiple instances, use `toot auth` to see all accounts, `toot activate` to switch between them, or use `--using myacc@myinstance.social` to override the currently active account.

Feedback is very welcome.

**Comment by jeroenpraat** [comment]
Great, thank you for your work! If I have time during the next couple of days, I will check it out.

**Comment by ihabunek** [comment]
@jeroenpraat i'd love to merge this by the end of the week, if you have some time on the weekend to check this it would be most appreciated.

**Comment by jeroenpraat** [comment]
Thank you fore remembering me. But can you tell me how to install this pull request? I have now installed toot via pip3, but to use the pull request I have to install it using git clone? Right? Can you explain how to do this, including the pull request?

**Comment by ihabunek** [comment]
You can install straight from branch using pip:
```
pip install git+https://github.com/ihabunek/toot.git@new-config
```
You need the pip which works with python3, so depending on your OS, it might be `pip3` instead of `pip`. You can check the version by running:
```
pip --version
```
you should get something like 
```
pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4)
```

**Comment by jeroenpraat** [comment]
Ok thanks, I succeeded to upgrade to that particular branch. First signs are good. Later this evening I gave you more results.

**Comment by jeroenpraat** [comment]
@ihabunek I tested all login related features with 3 accounts, from 2 different instances. And it works perfect!

Thanks!!!

**Comment by ihabunek** [comment]
Thanks for testing. I found an issue when there's no old config. Will fix that and release.

**Comment by jeroenpraat** [comment]
Oh yes, I only tested it with existing config. Thanks for your work!
