### ISSUE TITLE
all application faults return as one type of error code

### ISSUE THREAD

**Issue by memelord31337** [ihabunek/toot#333]
Greetings friends - please if you have some free time.

When toot experiences a server side failure it prompts with red text explaining the situation, invalid file, file too large etc.

Is there a way we can have different return codes rather than just 1?

The reason for this is when automating toot we can have various responses to different return codes.

**Comment by ihabunek** [comment]
Any particular errors you'd like reflected as distinct return codes?

**Comment by memelord31337** [comment]
Hello friend!

Thank you for asking - so far these are the particular errors we are seeing in significant volume:

XXXXX images are not supported

Validation failed: File content type is invalid, File is invalid

Error processing thumbnail for uploaded media

Validation failed: File must be less than 10 MB, File file size must be less than 10 MB

**Comment by ihabunek** [comment]
This is a bit tricky, the only data I get from the server is a text error, for example:

```json
{"error": "Validation failed: File content type is invalid, File is invalid"}
```

They don't provide an error code I could easily map onto return values.

In addition to that, there can be many errors in one message, like:

```json
{"error": "Validation failed: File content type is invalid, File is invalid, File must be less than 10 MB, File file size must be less than 10 MB"}
```

So I guess I could add a return value for errors starting with "Validation failed". Not sure if this would be useful.

Also this may vary from server to server, especially if using Pleroma or another implementation.

**Comment by danschwarz** [comment]
Do you get an HTTP 422 error code in this case? Returning the HTTP error code might provide some differentiation, although probably not as much as one would like...

**Comment by memelord31337** [comment]
@danschwarz - all 200's from client perspective as i'm aware, not seeing any HTTP specific issues, it's more along the lines of large files not being accepted (i believe this is a server side config somewhere to change the permitted size of the upload) and corrupted image files that load in more forgiving runtimes for images (browser, apple photos, Imessage, slack)

@ihabunek I understand your response - this explains why I couldn't find the output message when grepping the *.py files. 

I was hoping to be clever here and avoid using expect(1)

Perhaps I should dig deeper here.

**Comment by memelord31337** [comment]
expect(1) for the win. thanks for the consideration and chat.
