### ISSUE TITLE
Tests fail, no idea why

### ISSUE THREAD

**Issue by ihabunek** [ihabunek/toot#349]
e.g. https://github.com/ihabunek/toot/actions/runs/4563475451/jobs/8052008460

They work fine locally.

@danschwarz if you happen to have a little time could you check out why tests are not run?

**Comment by danschwarz** [comment]
The error running Pytest: "Error: Process completed with exit code 5." ?

Not sure why this is happening (and I'm not sure I have a way to debug it) but I'll do some googling and look into likely causes.

**Comment by danschwarz** [comment]
I just ran flake8 against `master` and it returns an error

`./toot/commands.py:10:1: F401 'toot.output.print_table' imported but unused`

but, having fixed that locally, I still get error 5 on `make test`

but running the individual commands within `make test` works OK.
I wonder if there's some kind of path issue going on with the github environment?

**Comment by danschwarz** [comment]
Tests are failing locally for me as well (Ubuntu 22.04).  pytest just isn't finding the test files in tests.
I've tried setting up a pytest.ini and manually specifying the location; no luck yet.
manually specifying the test files to test does work. Not sure what's going on.

**Comment by danschwarz** [comment]
I found that I can get pytest to run the tests properly if I specify the path in the makefile, I.e.

`pytest -v tests/*.py`

**Comment by ihabunek** [comment]
The funny thing is that I cannot reproduce this locally. It works fine on both my fedora/py3.11 and debian/py3.9 environments. 

P.S. Busy so didn't have time to sit down and test this properly. I'll have some time soon hopefully. And review your PRs too.

**Comment by ihabunek** [comment]
Finally sat down to debug this. I broke tests when refactoring integration tests. Fixed in cee289a391b9637dfe124447291af4e49c14da9c.
