### ISSUE TITLE
Latest (prerelease) version of urwid causes toot to stall at title screen until keyboard/mouse event

### ISSUE THREAD

**Issue by danschwarz** [ihabunek/toot#364]
See [this issue](https://github.com/urwid/urwid/issues/575) I've posted on the urwid site

**Comment by ihabunek** [comment]
@danschwarz I made a fix suggested by the urwid guys. Seems to work for me. Could you please verify it fixes the issue for you?

**Comment by danschwarz** [comment]
Confirmed that your fix works with the latest Urwid (which on my system is `urwid-2.3.5.dev22+gf809bfc`).

Because your fix calls `_loop.run_in_executor`, I wanted to verify that this internal call is available and working on older versions of Urwid as well, going back to Urwid 2.0.0 which is the earliest supported in `setup.py`.  I have tested and verified that it works with Urwid 2.1.2 and 2.1.0 which is the earliest we can actually run, now that we're using the urwidgets library.
