### ISSUE TITLE
Mastodon does (now) support max post length via API

### ISSUE THREAD

**Issue by andypiper** [ihabunek/toot#369]
Per this line and the surrounding comments

https://github.com/ihabunek/toot/blob/56cc056639bc40cc03c128ae2d134f57b6c481e6/toot/tui/app.py#L288

Mastodon does support an instance value in the API specifying the maximum post length (`GET /api/v1/instance` -> `configuration/statuses/max_characters`)

So this could now be reworked if desired.

Probably helpful for #144 / #248

**Comment by danschwarz** [comment]
Good catch. That attribute is supported by Mastodon 3.4.2+ so it would be useful for toot to check for it.

**Comment by ihabunek** [comment]
Thanks, fixed.
