### ISSUE TITLE
Persist / save TUI options

### ISSUE THREAD

**Issue by andypiper** [ihabunek/toot#371]
Currently there is no way to have the TUI default to `--relative-datetimes` or `--no-color`

It would be great if these could be persisted to the config file and overridden with the CLI options.

**Comment by danschwarz** [comment]
Your post made me realize that `toot tui --no-color` doesn't actually do anything. I submitted a PR to fix that.
Better config support is needed, I agree.

**Comment by danschwarz** [comment]
config options are a longstanding open issue.  one thing I realized after reading your comment is that --no-color actually doesn't work for the tui!  I have submitted a PR to fix that.

![image](https://github.com/ihabunek/toot/assets/3261094/15288612-831e-4ad5-8db0-ecc8d07df6fc)

**Comment by ihabunek** [comment]
@andypiper Implemented in 0.38.0

In `~/.config/toot/settings.toml`:

```toml
[commands.tui]
relative_datetimes = true
```

See docs:
https://toot.bezdomni.net/settings.html
