### ISSUE TITLE
Use toot as a library

### ISSUE THREAD

**Issue by davidbrochart** [ihabunek/toot#398]
I'm not sure if it's supported already, but is it possible to use toot as a library? I see it's mainly a CLI and a TUI, but I'm not sure if it's easy to use the underlying API.

**Comment by ihabunek** [comment]
Toot isn't designed to be used as a library. It can be used as a library, but it may not be very ergonomic and only covers the mastodon API which is used by the CLI/TUI.

As a short example, this load the currently active toot user and requests the credentials:

```py
from toot import api, config

user, app = config.get_active_user_app()
credentials = api.verify_credentials(app, user)
print(credentials)
```

Check out other functions in `toot.api`.

**Comment by davidbrochart** [comment]
Thanks!

**Comment by ihabunek** [comment]
@davidbrochart I must warn you that the API is not guaranteed to be be stable, I'm doing some changes right now which required me to change many api.* functions to return the http response, instead of the decoded body, which means in the next version you'll need to modify the code above from:

```py
api.verify_credentials(app, user)
```

to 

```py
api.verify_credentials(app, user).json
```

**Comment by davidbrochart** [comment]
Thanks for the heads up!
