### ISSUE TITLE
authentication failing on login

### ISSUE THREAD

**Issue by maddler** [ihabunek/toot#410]
Hello,
I've just installed Toot's latest version and trying to login via "toot login" but it fails with "Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method" error.

```
❯ toot env
toot 0.38.1
Python 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
macOS-14.1-x86_64-i386-64bit
```

Steps to reproduce

1. launch "toot login" on the command line
2. provide instance
3. provide login details
4. open provided link in browser

_Current outcome:_ error "Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."

_Expected outcome:_ authentication completed.

**Comment by dimkard** [comment]
I confirm this bug report. My env:
```
toot 0.38.1
Python 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
Linux-6.5.9-arch2-1-x86_64-with-glibc2.38
```

**Comment by maddler** [comment]
Yes, the error is being shown in the browser.
![image](https://github.com/ihabunek/toot/assets/302261/1dbe1426-3299-4463-bab2-fc0c2e896697)
Server is https://mastodon.ie.

**Comment by dimkard** [comment]
Same for me, server: floss.social

**Comment by ihabunek** [comment]
I registered on floss.social to try to reproduce this, but did not have any issues. Server gave me the code after logging in.  :thinking: 

![image](https://github.com/ihabunek/toot/assets/482138/f816f570-6aad-4b7e-ab42-f98de27b27b6)

**Comment by maddler** [comment]
uhm, I've got 2FA enabled. That or anything else in the account preferences?

But with tut it works fine and the generated URL looks pretty much the same.

**Comment by maddler** [comment]
So, I removed  an existing config.json file (was trying to login again as I was getting some session errors, if I recall correctly, before) and that's working now.

**Comment by ihabunek** [comment]
It's something with the client registration. Could you please edit your `~/.config/toot/config.json` and remove the entry for `floss.social`? The part outlined in red here:

![image](https://github.com/ihabunek/toot/assets/482138/7615c7bc-660b-4990-a028-a9c94ec23805)

And then try to log in again, it will create another client id.

**Comment by ihabunek** [comment]
> So, I removed an existing config.json file

Yeah, that would work too.

**Comment by maddler** [comment]
Thanks for your help!
