### ISSUE TITLE
BREAKING: toot 0.40.0 `post` command no longer accepts `-u`/`--using`

### ISSUE THREAD

**Issue by kseistrup** [ihabunek/toot#448]
Now that `toot post -u|--using` no longer works (which is an unlisted breaking change), how are we supposed to specify which account to post as?

**Comment by ihabunek** [comment]
This is a bug, I'll fix it but not today. Please downgrade to 0.39.0 until I can produce a patch.

**Comment by ihabunek** [comment]
I decided to make this another breaking change, since I'm already breaking things. Added to changelog for 0.40.0.

Please upgrade to 0.40.1 and use `toot --as <account> post`. This option works for all commands, not just post.

**Comment by kseistrup** [comment]
> Please upgrade to 0.40.1 and use `toot --as <account> post`.

That's a lot of scripts to have to rewrite. Was it really impossible to keep the old `-u`/`--using` option so as to not make it a breaking change?

**Comment by kseistrup** [comment]
While I respect your right to make as many breaking changes as you like, whenever you like, I would like to present how the situation looks from here:

Had `-us`/`--using` not been changed to `--as` in this commit, the breaking changes in v0.40.0 would not have affected me _at all_. Now I have in the ballpark of 75 shell scripts that are using `toot` to automate posting to the fediverse, and because other commands in these shell scripts may be using `-u` or `--using`, and because around a third of the scripts have the option on a line or two below the `toot post` (in order to avoid excessively long lines), it is unfortunately not as simple as running `sed -i s/--using/--as/g` on all the scripts. Instead I now have to go through each script manually to make it conform to the new syntax with `--as`, and while I do this I have to stop auto-posting.

Indeed a breaking change.

It would be interesting to hear why you felt it was so important to change a word from `--using` to `--as` and thus with certainty break everything for people who are posting from more than one account, rather than just using the same option as before and only break something for a fraction of said users.

**Comment by ihabunek** [comment]
I'll undo the break, but have limited time these days. Please a little patience.

-- Ivan

**Comment by ihabunek** [comment]
Please check out 0.40.2, the option has been restored.

**Comment by kseistrup** [comment]
That's really, really nice. Thanks a lot! :pray:
