### ISSUE TITLE
Wide characters break layout

### ISSUE THREAD

**Issue by ihabunek** [ihabunek/toot#45]
e.g. chinese and japanese script, some emojis, etc.

Check out:
https://github.com/jquast/wcwidth

**Comment by dheadshot** [comment]
I'm finding that *none* of the lines fit the screensize! 
![ss1](https://user-images.githubusercontent.com/19638574/44279079-0a5cd080-a248-11e8-9d3e-a35df55ebd21.png)

**Comment by ihabunek** [comment]
`toot timeline` is basically unfinished, i should document this. In the meantime check out `toot curses` which is nicer & interactive.

**Comment by ihabunek** [comment]
This should be much better now. Still need to implement setting the screen width to fit the terminal. Currently hardcoded to 100 chars wide.
