### ISSUE TITLE
silent posting

### ISSUE THREAD

**Issue by anarcat** [ihabunek/toot#46]
could it be possible to implement a silent posting mechanism, like a `--quiet` flag? i am using this program in a batch script and it's annoying to silence its output, because it means I hide possible failures...

thanks!

**Comment by ihabunek** [comment]
That should be simple to implement. But you can also just redirect stdout to `/dev/null` since all errors are written to stderr.

**Comment by ihabunek** [comment]
@anarcat I added a `--quiet` flag which can be applied to any command to disable output to stdout on success. Errors will still be written to stderr. Does that work for you? Will be released in v0.19 soon.

**Comment by anarcat** [comment]
i haven't tried it but it looks pretty much like what i need, thanks!
