### ISSUE TITLE
post in markdown from commandline

### ISSUE THREAD

**Issue by lucajet** [ihabunek/toot#477]
Hello, i'm  using a pleroma server.

Would be possible , from command line, to "toot post" using markdown instead of plain text?

something like 

> toot post -v public "__bold__ and _italic_ "

**Comment by ihabunek** [comment]
Try this:

```
toot post --content-type "text/markdown" ...
```

**Comment by lucajet** [comment]
i see, thank you!

**Comment by ihabunek** [comment]
You can also set a default value for this by defining an environment variable like this (for linux):

```
export TOOT_POST_CONTENT_TYPE="text/markdown" 
```
