### ISSUE TITLE
Images appear garbled in terminal.app on macOS

### ISSUE THREAD

**Issue by nathnp** [ihabunek/toot#483]
Images viewed in macOS terminal.app appear garbled when using `toot tui`.

This does not occur when using Kitty on macOS. Or on my Fedora 40 Linux machine.

toot version: toot v0.43.0
macOS version: 14.4.1

<figure>
<img width="1680" alt="Screenshot 2024-05-01 at 23 42 17" src="https://github.com/ihabunek/toot/assets/57642318/a37bdbf4-e228-4cad-b2a1-7ffdfc707ac7">
<figcaption>terminal.app in macOS</figcaption>
<figure>
<hr>
<figure>
<img width="1680" alt="Screenshot 2024-05-01 at 23 42 35" src="https://github.com/ihabunek/toot/assets/57642318/3b87b4c1-d86e-46ec-944c-2d7b10731ebd">
<figcaption>Kitty on macOS</figcaption>
</figure>

**Comment by danschwarz** [comment]
The limitation here is that MacOS terminal app supports only 256 colors - not truecolor.  

It is possible to support image rendering with a 256 color palette, but we will need support from term-image to implement that. The feature request is open with term-image here: [https://github.com/AnonymouX47/term-image/issues/90](https://github.com/AnonymouX47/term-image/issues/90)

In the meantime I recommend using [iterm2](https://iterm2.com/) on MacOS.

**Comment by mihkelraba** [comment]
I'll add this comment here, because it fits to the same topic.
Kitty shows images, but they are very low res / blurry.

![image](https://github.com/ihabunek/toot/assets/53609335/fb7805f2-129b-4f63-b033-5a191f1e24eb)

In browser
![image](https://github.com/ihabunek/toot/assets/53609335/edfcb795-9b9a-419b-bc59-61e8bb1fd703)

**Comment by danschwarz** [comment]
Are you launching the tui like this: `toot tui -f kitty`? If not,`toot tui` defaults to the Unicode block graphics you're seeing.

Alternatively, you can set the `image_format` variable in the `settings.toml` file to `'kitty'` if you're confident you will only launch the tui from within kitty terminal.

**Comment by mihkelraba** [comment]
> Are you launching the tui like this: `toot tui -f kitty`? If not,`toot tui` defaults to the Unicode block graphics you're seeing.
> 
> Alternatively, you can set the `image_format` variable in the `settings.toml` file to `'kitty'` if you're confident you will only launch the tui from within kitty terminal.

Tried your command & also adding image_format = "kitty" into config file.
Images are not displayed anymore, but instead some data is displayed on menubar

![image](https://github.com/ihabunek/toot/assets/53609335/1144af79-e5d8-4b72-801f-3d83817fe07f)

**Comment by danschwarz** [comment]
OK, so what's going on there is that your terminal is misinterpreting command sequences as text data.  Possibilities:

1. Are you using a recent version of kitty? If you're using an old version, try updating to the latest.
2. Are you running a screen multiplexer like `screen` or `tmux`?  These could interfere with the terminal command sequences.
3. Timing could be to blame; are you running the terminal directly on the system that is executing `toot tui`?  Or are you connecting over one or more network hops?  Are any of these hops particularly slow?

**Comment by AnonymouX47** [comment]
Hello here!

Firstly, I should apologize for not responding since I got pinged. It was actually intentional as I didn't want to make any promises I would end up breaking but rather planned to respond with the feature implemented.

As earlier implied, I have now implemented indexed-color (256-color) support in https://github.com/AnonymouX47/term-image/pull/109 (please, take note of the admonition there).

@nathnp, I don't know what installation method you used for `toot` but if possible, please run

```shell
pip install git+https://github.com/AnonymouX47/term-image.git@indexed-color
```
or its equivalent within the same environment as you have `toot` installed and report back on how image display is within `toot` after that.

Thank you very much. :smiley:

**Comment by danschwarz** [comment]
@AnonymouX47  is the indexed color support reliant on any terminal queries? I have disabled term-image terminal queries in the toot tui integration. I expect I'll have to provide an option flag to control indexed color mode usage.

**Comment by AnonymouX47** [comment]
> @AnonymouX47  is the indexed color support reliant on any terminal queries?

Not at all.

> I have disabled term-image terminal queries in the toot tui integration.

Yeah, I noticed. You actually don't have much to loose.

> I expect I'll have to provide an option flag to control indexed color mode usage.

Yes, sure. The most straight-forward method (which is the best in the case of toot) would be:

```py
# Use indexed-color
BlockImage.set_render_method("INDEXED")

# Use direct-color (default)
BlockImage.set_render_method("DIRECT")
```

**Comment by rvyhvn** [comment]
> Are you running a screen multiplexer like screen or tmux? These could interfere with the terminal command sequences.

i'm using tmux, any workaround how to solve the images are not rendered? tmux is on top of kitty, if i don't use `-f kitty`, it's bitmapped, but if i use `-f kitty` the images are not being shown.
