### ISSUE TITLE
Option to accept all HTTPS certificates

### ISSUE THREAD

**Issue by marnanel** [ihabunek/toot#55]
It would be useful to have a commandline option to accept all HTTPS certificates. When you're testing a new server, especially one on an intranet, it's common not to have a valid certificate for that server.

This isn't trivial to implement at present; it requires "valid" to be set on the Session object in send_request() in api.py. send_request() is called from all over the place, so adding a new parameter will be messy; there's also no global state to store this in.

Another possibility is to allow the use of HTTP as well as HTTPS.

**Comment by ihabunek** [comment]
This has been implemented in #80 and released in v.0.20.0.

You can use `toot login --disable-https ` to use http.
