### ISSUE TITLE
toot post could use a CW argument

### ISSUE THREAD

**Issue by matthewgraybosch** [ihabunek/toot#63]
I'd like to specify a content warning when posting using "toot post", but I don't see an option for that in "toot post --help". Are CWs implemented in toot?

**Comment by ihabunek** [comment]
I added it in fa4e4e6357924df8ec21baca4136350f964b8355, will be in next release.

**Comment by matthewgraybosch** [comment]
Awesome. Now I can CW my weekly "Please buy my novels" auto-toots as the advertisements they are. Thanks!
