### ISSUE TITLE
How to reply?  ID not available from timeline!

### ISSUE THREAD

**Issue by dheadshot** [ihabunek/toot#73]
There *is* a method for replying to posts given their ID.  That's fine.  The problem is that the `timeline` output doesn't actually show the post ID!  In other words, how do I find out the ID in order to reply to a post from the timeline?!

Thanks in advance.

**Comment by ihabunek** [comment]
There is currently no way of telling the ID, except when you post your own toots in which case you get an ID back as part of the URL.

**Comment by ihabunek** [comment]
This will be available in timeline and thread in next version (0.21.0), released soon.
