### ISSUE TITLE
Possibility to boost a post - feature request

### ISSUE THREAD

**Issue by nils-van-zuijlen** [ihabunek/toot#75]
Would it be possible to boost a post (RT) using your tool ?

**Comment by nils-van-zuijlen** [comment]
I think of a command like `toot boost <id-of post>`

**Comment by ihabunek** [comment]
This has been implemented. I used the opportunity to add other status-related commands. Check out 82ed630864592ba19d84a809ef27664205d2ead4.

I used "reblog" instead of "boost" since that's what mastodon uses.

Will be released in 0.20.0 one of these days.

**Comment by ihabunek** [comment]
Also added to `toot curses` by pressing "b".
