### ISSUE TITLE
toot now in AUR

### ISSUE THREAD

**Issue by dadosch** [ihabunek/toot#79]
I just wanted to ping you. toot has been added to the Arch Linux User Repository https://aur.archlinux.org/packages/toot/ (something like PPAs with Ubuntu). If you want, you can add it to the README. :smiley: 

Thank you for this great piece of software :+1:

**Comment by ihabunek** [comment]
@dadosch That's very kind of you. Thanks for letting me know. I'll leave the issue open so I remember to add it to the README.

**Comment by ihabunek** [comment]
@dadosch To install toot, an Arch user needs only to `pacman -S toot` or is there some other action required?

**Comment by dadosch** [comment]
@ihabunek an Arch user needs to use a AUR Helper like yay, so it would be `yay -S toot`

**Comment by ihabunek** [comment]
@dadosch Thanks again, Added the instructions. If you'd like to be mentioned as maintainer, let me know which name and contact (e.g. email) you'd like shown in the docs.

Just a heads-up, the next version will have an additional dependancy on the wcwidth python package.
