### ISSUE TITLE
Feature request: toot post via stdin

### ISSUE THREAD

**Issue by ddevault** [ihabunek/toot#82]
Would be nice for writing multi-line posts

**Comment by ihabunek** [comment]
You can already do this, see [usage examples](https://toot.readthedocs.io/en/latest/usage.html#examples).

It should be documented in `toot post --help` I guess.

**Comment by ddevault** [comment]
Ah, cool. This doesn't work if stdin is a tty, though. I want to type the message straight into my terminal.

**Comment by ihabunek** [comment]
Steps to reproduce?

**Comment by ddevault** [comment]
```
~ > toot post
You must specify either text or media to post.
```

**Comment by ihabunek** [comment]
Expected behaviour would be like running `cat | toot post`?

**Comment by ddevault** [comment]
Aye

**Comment by ihabunek** [comment]
Makes sense, I'll look into it.

**Comment by ddevault** [comment]
Thanks!
