### ISSUE TITLE
Reverse Order of Timeline

### ISSUE THREAD

**Issue by mantlepro** [ihabunek/toot#9]
It would be better to display the timeline in reverse order with newest items at the bottom, closest to the prompt. This is especially desirable when the terminal window is too small to display the entire query.

With the order reversed, the `toot timeline` command can be run to see the latest as the last returned without scrolling to the top of the heap.

Anyway, thanks for an awesome CLI!

**Comment by ihabunek** [comment]
I can add that as a param, but I'm planning to replace that command in favour of a curses app.

Try `toot curses` for an early demo. Python 3 only for now.

**Comment by ihabunek** [comment]
`toot timeline` is superceded by `toot curses` so I will not be doing further work on supporting this command.
