### ISSUE TITLE
$EDITOR support

### ISSUE THREAD

**Issue by msnyder-info** [ihabunek/toot#90]
I'd like to be able to enter `toot post` at the command line, with some argument which opens $EDITOR to a temporary file whose contents are then posted to the timeline.

**Comment by joss-rendall** [comment]
Hy !
I wrote this script - maybe it can inspire you?
It allows to write another provisional script that runs several Toot commands one after the other.
The purpose is to publish an existing image list in a directory (cd/to-Toot).
The script lists images or files, turns it into a script with several Toot commands, breaks every 30 files (Mastodon limitation?)
[_made-sh-to-toot.zip](https://github.com/ihabunek/toot/files/2856888/_made-sh-to-toot.zip)

**Comment by msnyder-info** [comment]
Thanks! I'll take a look at it.

**Comment by ihabunek** [comment]
This has been implemented in d21cad8. Still need to add docs. Will be available in next release.

It will work like this if you have $EDITOR set:
```
toot post -e
```

Or you can override the editor:
```
toot post -e vim
```
