### ISSUE TITLE
Include Makefile in release tarball

### ISSUE THREAD

**Issue by trondd555** [ihabunek/toot#91]
You include tests in the release tarball but not the Makefile which defines how to run them.  Would it be possible to include the Makefile in the release tarball?  It's used by the OpenBSD ports system when creating the package in order to run the tests.

This would help verify functionality and keep the port  up with changes you might make to test execution.

**Comment by ihabunek** [comment]
Sure, I'll add it to the next release.

**Comment by ihabunek** [comment]
Included in the latest release:
 https://github.com/ihabunek/toot/releases/tag/0.21.0

**Comment by dadosch** [comment]
From AUR:
> there's a /usr/Makefile in the package, which probably isn't intended. Could u pls remove that ? Thx.

The Makefile also gets included if you do a regular `setup.py install` which shouldn't be the case I suppose?

**Comment by ihabunek** [comment]
@trondd555 I'm going to revert this change for now, since including the Makefile is causing problems to multiple other users, and I can't figure out how to include the Makefile without it being installed. Let me know if you have any ideas.

**Comment by trondd555** [comment]
Not a python person, but searching around there seems to be a couple options ranging from overriding setup.py functions to using manifest files.  I don't know what the best thing would be to do.

If no one else knows, I'll try out some of the options when I get a chance.
